#! /bin/sh

# Kill for restarting bspwm
killall -q picom

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Borders
bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#Startup
picom -b &
sxhkd &
dunst &
feh --bg-fill $HOME/.config/images/3.jpg
